#!/usr/bin/bash

set -e

PI=3.14159265358979

EXEC="./build/examples/rolling_shutter"

FPS=60 # frames per second
RPS=1 # rotaions per second
EXPOSURE_TIME=$(echo "0.8/${FPS}" | bc -l)
FREQUENCY=$(echo "2.0 * ${PI} * ${RPS}" | bc -l)
EXEC_ARGS="--frequency ${FREQUENCY} --num_blades 5 --exposure_time ${EXPOSURE_TIME} --motion_blur ${EXPOSURE_TIME}"
OUT_DIR="./out/movie"
SAMPLES=10
SAVE_FREQUENCY=${SAMPLES}
RAY_DEPTH=50
RESOLUTION_FACTOR=2 # >= 2

FRAME_START=0
FRAME_STOP=120

function timestamp {
    echo "        $(date +%H:%M:%S)"
}

function ppm {
    FRAME=$1
    echo "${OUT_DIR}/${FRAME}.ppm"
}

function png {
    FRAME=$1
    echo "${OUT_DIR}/${FRAME}.png"
}

function convert2png {
    FRAME=$1
    pnm2png $(ppm ${FRAME}) $(png ${FRAME}) \
    && rm $(ppm ${FRAME})
}

function render_frame {
    FRAME=$1
    TIME=$(echo "${FRAME}/${FPS}" | bc -l)
    echo "frame = ${FRAME}, time = ${TIME}"
    ${EXEC} \
    --out $(ppm ${FRAME}) \
    --save_frequency ${SAVE_FREQUENCY} \
    --samples ${SAMPLES} \
    --ray_depth ${RAY_DEPTH} \
    --resolution_factor ${RESOLUTION_FACTOR} \
    --time ${TIME} \
    ${EXEC_ARGS} \
    > /dev/null

}

function make_frames {
    timestamp
    for FRAME in $(seq -f "%05g" ${FRAME_START} ${FRAME_STOP})
    do
        render_frame ${FRAME}
        convert2png ${FRAME}
        timestamp
    done

}

function make_mp4 {
    ffmpeg -r 60 -i $(png "%05d") -vcodec libx264 -pix_fmt yuv420p "${OUT_DIR}/mov.mp4"
}


# ENTRY POINT

make "${EXEC}"
mkdir -p "${OUT_DIR}"

echo "make movie for ${EXEC}:"
make_frames
make_mp4
